workflows:
  android-build:
    name: Android Build
    max_build_duration: 30
    environment:
      flutter: 3.22.0
    scripts:
      - name: Get packages
        script: cd android-source && flutter pub get
      - name: Build APK
        script: cd android-source && flutter build apk --release
    artifacts:
      - android-source/build/app/outputs/flutter-apk/app-release.apk

  ios-build:
    name: iOS Build
    max_build_duration: 30
    environment:
      flutter: 3.22.0
      xcode: 16.0
      cocoapods: default
    scripts:
      - name: Get packages
        script: cd ios-source && flutter pub get
      - name: Build iOS
        script: |
          cd ios-source
          flutter build ios --release --no-codesign
    artifacts:
      - ios-source/build/ios/iphoneos/Runner.app